### ISSUE TITLE
Bootstrap logo says Boostrap

### ISSUE THREAD

**Issue by dotfold** [totaljs/website#5]
The asset located at:
`https://www.totaljs.com/img/logo-bootstrap.png`

Says "Boostrap" not "Bootstrap".

![screen shot 2015-02-24 at 2 05 21 pm](https://cloud.githubusercontent.com/assets/502910/6342522/57cf5544-bc2e-11e4-9d64-c0d0416622c9.png)

**Comment by petersirka** [comment]
Ohhhhhhh shit, my inattention.
I fixed it. Thanks.
